CREATE TABLE IF NOT EXISTS line_campaigns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  segment VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,
  target_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
